# Generated by Django 6.0 on 2025-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.TextField()),
                ('hero_image', models.ImageField(upload_to='home/hero/')),
                ('admission_title', models.CharField(max_length=200)),
                ('admission_description', models.TextField()),
                ('admission_image', models.ImageField(upload_to='home/admission/')),
                ('about_title', models.CharField(max_length=200)),
                ('about_description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
